name: manuel_plug
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.10
  - lxml
  - pydantic
  - toml
  - six
  - pip
  - pyannote.core
  - pip:
      - git+https://github.com/m-bain/whisperx.git
      - google
      - gailbot
      - gailbottools==0.0.9
      - dict-to-dataclass
